---
- name: Setup Homebrew and Software
  hosts: localhost
  tasks:
    - name: Register Package List
      command: awk '{print $1}' Brew_Packages.txt
      register: _pkgs
      delegate_to: localhost
      run_once: true

    - name: List Packages to be installed$
      debug:$
        var: _pkgs

    - name: Install Packages
      homebrew: 
        name: "{{ _pkgs.stdout_lines }}"
        state: present
